# Generated by Django 4.1.3 on 2026-07-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_core_baseli_pub_dat_7d2a1c_idx_core_baseli_pub_dat_4ba1e2_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rsssource',
            options={'ordering': ['priority', 'name'], 'verbose_name': 'RSS Source', 'verbose_name_plural': 'RSS Sources'},
        ),
        migrations.AddField(
            model_name='rsssource',
            name='priority',
            field=models.PositiveIntegerField(default=100, help_text='عدد کوچک\u200cتر = اولویت بالاتر (۱ بهتر از ۲).'),
        ),
    ]
