# Generated by Django 5.2.17 on 2026-09-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rsssource_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='content_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='editorial_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
